config/routes.rb
Rails.application.routes.draw do

get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'

resources :users
resources :sessions

root 'organizations#index'

  get 'enablers/' => 'enablers#index', as: :enablers
  get 'enablers/new' => 'enablers#new', as: :new_enabler
  get 'enablers/:id' => 'enablers#show', as: :enabler
  post 'enablers/' => 'enablers#create', as: :create_enabler
  get 'enablers/:id/edit' => 'enablers#edit', as: :edit_enabler
  patch 'enablers/:id' => 'enablers#update', as: :update_enabler
  delete 'enablers/:id' => 'enablers#destroy', as: :delete_enabler

  get 'organizations/' => 'organizations#index', as: :organizations
  get 'organizations/new' => 'organizations#new', as: :new_organization
  get 'organizations/:id' => 'organizations#show', as: :organization
  post 'organizations/' => 'organizations#create', as: :create_organization
  get 'organizations/:id/edit' => 'organizations#edit', as: :edit_organization
  patch 'organizations/:id' => 'organizations#update', as: :update_organization
  delete 'organizations/:id' => 'organizations#destroy', as: :delete_organization

end

app/models/enabler.rb
class Enabler
  include Mongoid::Document
  field :prefix, type: String
  field :firstname, type: String
  field :lastname, type: String
  field :suffix, type: String
  field :jobtitle, type: String
# should I have an org here, since I will have a connection through the relationship?
  field :org, type: String
  field :email, type: String
  field :altemail, type: String
  field :ct_enabler_type, type: String
  field :mobiletel, type: String
  field :officetel, type: String
  field :hometel, type: String
  field :fax, type: String
  field :indiv_web_url, type: String
  field :indiv_description, type: String
  field :indiv_notes, type: String
  field :work_address_street, type: String
  field :work_address_city, type: String
  field :work_address_state, type: String
  field :work_address_zip, type: String
  field :home_address_street, type: String
  field :home_address_city, type: String
  field :home_address_state, type: String
  field :home_address_zip, type: String
  field :spousal_status, type: String
  field :spouse_name, type: String
  field :orientation, type: String
  field :gender, type: String
  field :ethnicity, type: String
  field :country_of_origin, type: String
# should I have an org here, since I will have a deals model and a connection through the relationship?
  field :major_deals, type: String
# if i want this to be a text_area, do I have to define that here?
  field :staff_notes, type: String
  field :social_twitter, type: String
  field :social_linkedin, type: String
  field :social_facebook, type: String
  field :social_googleplus, type: String
  field :social_youtube, type: String
  field :social_pinterest, type: String
  field :social_instagram, type: String
  field :social_flickr, type: String
  field :social_blog, type: String
  field :social_platform_dominant, type: String
  field :date_last_updated, type: DateTime
end

app/controllers/enablers_controller.rb
class EnablersController < ApplicationController
	
# before_action :make_sure_logged_in

before_filter :authorize

	def index
		@enablers = Enabler.all
	end

	def show
		@enabler = Enabler.find(params[:id])
	end

	def new
		@enabler = Enabler.new
	end

	def create
		@enabler = Enabler.new(ena_user_params)
		if @enabler.save
			redirect_to enablers_path
		else
			render 'new'
		end
	end

	def edit
		@enabler = Enabler.find(params[:id])
	end

	def update
		@enabler = Enabler.find(params[:id])
		if @enabler.update_attributes(ena_user_params)
			redirect_to enablers_path
		else
			render 'edit'
		end
	end

	def destroy
		@enabler = Enabler.find(params[:id])
		@enabler.destroy
		redirect_to enablers_path
	end

private

	# def make_sure_logged_in
	# 	if !current_user
	# 	redirect_to new_session_path
	# 	end
	# end

	def ena_user_params
      params.require(:enabler).permit(
		:prefix, 
		  :firstname, 
		  :lastname, 
		  :suffix, 
		  :jobtitle, 
		# should I have an org here, since I will have a connection through the relationship?
		  :org, 
		  :email, 
		  :altemail, 
		  :ct_enabler_type, 
		  :mobiletel, 
		  :officetel, 
		  :hometel, 
		  :fax, 
		  :indiv_web_url, 
		  :indiv_description, 
		  :indiv_notes, 
		  :work_address_street, 
		  :work_address_city, 
		  :work_address_state, 
		  :work_address_zip, 
		  :home_address_street, 
		  :home_address_city, 
		  :home_address_state, 
		  :home_address_zip, 
		  :spousal_status, 
		  :spouse_name, 
		  :orientation, 
		  :gender, 
		  :ethnicity, 
		  :country_of_origin, 
		# should I have an org here, since I will have a deals model and a connection through the relationship?
		  :major_deals, 
		# if i want this to be a text_area, do I have to define that here?
		  :staff_notes, 
		  :social_twitter, 
		  :social_linkedin, 
		  :social_facebook, 
		  :social_googleplus, 
		  :social_youtube, 
		  :social_pinterest, 
		  :social_instagram, 
		  :social_flickr, 
		  :social_blog, 
		  :social_platform_dominant, 
		  :date_last_updated
		)
    end
end

app/helpers/enablers_helper.rb
module EnablersHelper
end

app/views/enablers/_form_new_edit.html.erb
<%= form_for @enabler do |f| %>

<div class="wrapper_div">
	<div class="center_div">
		<table>
			<thead>
			<tr class="row_odd">
				<th colspan="2"><h1>ADD a NEW "Enabler" Executive</h1></th>
			</tr>
			</thead>
			<tbody>
			<tr>
				<td><br>Prefix or Honorific/Rank:
				</td>
				<td><br><%= f.text_field :prefix, :placeholder => "exs: Mr, Ms, Dr, Hon, COL" %>
				</td>
			</tr>
			<tr>
				<td>First Name:</td>
				<td><%= f.text_field :firstname %></td>
			</tr>
			<tr>
				<td>Last Name:</td>
				<td><%= f.text_field :lastname %></td>
			</tr>
			<tr>
				<td>Suffix:</td>
				<td><%= f.text_field :suffix %></td>
			</tr>
			<tr>
				<td>Job Title:</td>
				<td><%= f.text_field :jobtitle %></td>
			</tr>
			<tr>
				<td>Organization:</td>
				<td><%= f.text_field :org %></td>
			</tr>
			<tr>
				<td>Email Address, Main:</td>
				<td><%= f.text_field :email %>
				</td>
			</tr>
			<tr>
				<td>Alternate Email:</td>
				<td><%= f.text_field :altemail %></td>
			</tr>
			<tr>
				<td>Type of Enabler:</td>
				<td><%= f.text_field :ct_enabler_type %></td>
			</tr>
			<tr>
				<td>Mobile Tel:</td>
				<td><%= f.text_field :mobiletel %></td>
			</tr>
			<tr>
				<td>Office Tel:</td>
				<td><%= f.text_field :officetel %></td>
			</tr>
			<tr>
				<td>Home Tel:</td>
				<td><%= f.text_field :hometel %></td>
			</tr>
			<tr>
				<td>Fax:</td>
				<td><%= f.text_field :fax %></td>
			</tr>
			<tr>
				<td>Individual's Website Url:</td>
				<td><%= f.text_field :indiv_web_url %></td>
			</tr>
			<tr>
				<td>Individual's Description:</td>
				<td><%= f.text_field :indiv_description %></td>
			</tr>
			<tr>
				<td>Individual Notes:</td>
				<td><%= f.text_field :indiv_notes %></td>
			</tr>
			<tr>
				<td>Work Address Street:</td>
				<td><%= f.text_field :work_address_street %></td>
			</tr>
			<tr>
				<td>Work Address City:</td>
				<td><%= f.text_field :work_address_city %></td>
			</tr>
			<tr>
				<td>Work Address State:</td>
				<td><%= f.text_field :work_address_state %></td>
			</tr>
			<tr>
				<td>Work Address Zip:</td>
				<td><%= f.text_field :work_address_zip %></td>
			</tr>
						<tr>
				<td>Home Address Street:</td>
				<td><%= f.text_field :home_address_street %></td>
			</tr>
			<tr>
				<td>Home Address City:</td>
				<td><%= f.text_field :home_address_city %></td>
			</tr>
			<tr>
				<td>Home Address State:</td>
				<td><%= f.text_field :home_address_state %></td>
			</tr>
			<tr>
				<td>Home Address Zip:</td>
				<td><%= f.text_field :home_address_zip %></td>
			</tr>
			<tr>
				<td>Spousal Status:</td>
				<td><%= f.text_field :spousal_status %></td>
			</tr>
			<tr>
				<td>Spouse's Name:</td>
				<td><%= f.text_field :spouse_name %></td>
			</tr>
			<tr>
				<td>Orientation:</td>
				<td><%= f.text_field :orientation %></td>
			</tr>
			<tr>
				<td>Gender:</td>
				<td><%= f.text_field :gender %></td>
			</tr>
			<tr>
				<td>Ethnicity/Race:</td>
				<td><%= f.text_field :ethnicity %></td>
			</tr>
			<tr>
				<td>Country of Origin:</td>
				<td><%= f.text_field :country_of_origin %></td>
			</tr>
			<tr>
				<td>Major Deals:</td>
				<td><%= f.text_field :major_deals %></td>
			</tr>
			<tr>
				<td>Staff Notes:</td>
				<td><%= f.text_field :staff_notes %></td>
			</tr>
			<tr>
				<td>Twitter Account Link:</td>
				<td><%= f.text_field :social_twitter %></td>
			</tr>
			<tr>
				<td>Linked-In Account Link:</td>
				<td><%= f.text_field :social_linkedin %></td>
			</tr>
			<tr>
				<td>Facebook Account Link:</td>
				<td><%= f.text_field :social_facebook %></td>
			</tr>
			<tr>
				<td>Google + Account Link:</td>
				<td><%= f.text_field :social_googleplus %></td>
			</tr>
			<tr>
				<td>YouTube Account Link:</td>
				<td><%= f.text_field :social_youtube %></td>
			</tr>
			<tr>
				<td>Pinterest Account Link:</td>
				<td><%= f.text_field :social_pinterest %></td>
			</tr>
			<tr>
				<td>Instagram Account Link:</td>
				<td><%= f.text_field :social_instagram %></td>
			</tr>
			<tr>
				<td>Flickr Account Link:</td>
				<td><%= f.text_field :social_flickr %></td>
			</tr>
			<tr>
				<td>Blog Link:</td>
				<td><%= f.text_field :social_blog %></td>
			</tr>
			<tr>
				<td>Dominant/Preffered Social Media Platform:</td>
				<td><%= f.text_field :social_platform_dominant %></td>
			</tr>
			<tr>
				<td>Date Last Updated:</td>
				<td><%= f.datetime_field :date_last_updated %></td>
			</tr>
			<tr>
            	<td> </td>
            	<td><%= f.submit "Submit" %></td>
         	</tr>
			</tbody>
		</table>
	</div>
</div>

<% end %>

app/views/enablers/edit.html.erb
<h1>Edit an Enabler Executive</h1>

<%= render 'form_new_edit' %>

app/views/enablers/index.html.erb
		<table>
			<thead>
			<tr class="row_odd">
				<th colspan="5"><h1 style="margin:20px">VIEW the Executive "Enablers" of Innovation</h1></th>
			</tr>
			<tr>
				<th><h2><u>First Name</u></h2></th>
				<th><h2><u>Last Name</u></h2></th>
				<th><h2><u>Job Title</u></h2></th>
				<th><h2><u>Organization</u></h2></th>
				<th><h2><u>Actions</u></h2></th>
			</thead>
			<tbody>
		<% @enablers.each do |enabler| %>
			<tr>
				<td><strong><%= enabler.firstname %></strong>
				</td>
				<td><strong><%= enabler.lastname %></strong>
				</td>
				<td><%= enabler.jobtitle %></strong>
				</td>
				<td><%= enabler.org %></strong>
				</td>
				<td>
				<ul>
						<li><%= link_to 'Details', enabler %></li>
						<li><%= link_to 'Edit', edit_enabler_path(enabler) %></li>
						<li><%= link_to 'Delete', enabler, method: :delete, data: { confirm: 'Are you sure?' } %></li>
					</ul>
				</td>
			</tr>
			<% end %>
			</tbody>
		</table>

app/views/enablers/new.html.erb
<%= render 'form_new_edit' %>

app/views/enablers/show.html.erb
		<table>
			<thead>
			<tr>
				<th colspan="2"><h1 style="margin:20px">VIEW This Technology Executive "Enabler"</h1></th>
			</tr>
			</thead>
			<tbody>
			<tr>
				<td>Prefix or Honorific/Rank:
				</td>
				<td><%= @enabler.prefix %>
				</td>
			</tr>
			<tr>
				<td>First Name:</td>
				<td><%= @enabler.firstname %></td>
			</tr>
			<tr>
				<td>Last Name:</td>
				<td><%= @enabler.lastname %></td>
			</tr>
			<tr>
				<td>Suffix:</td>
				<td><%= @enabler.suffix %></td>
			</tr>
			<tr>
				<td>Job Title:</td>
				<td><%= @enabler.jobtitle %></td>
			</tr>
			<tr>
				<td>Organization:</td>
				<td><%= @enabler.org %></td>
			</tr>
			<tr>
				<td>Email Address, Main:</td>
				<td><%= @enabler.email %>
				</td>
			</tr>
			<tr>
				<td>Alternate Email:</td>
				<td><%= @enabler.altemail %></td>
			</tr>
			<tr>
				<td>Type of Enabler:</td>
				<td><%= @enabler.ct_enabler_type %></td>
			</tr>
			<tr>
				<td>Mobile Tel:</td>
				<td><%= @enabler.mobiletel %></td>
			</tr>
			<tr>
				<td>Office Tel:</td>
				<td><%= @enabler.officetel %></td>
			</tr>
			<tr>
				<td>Home Tel:</td>
				<td><%= @enabler.hometel %></td>
			</tr>
			<tr>
				<td>Fax:</td>
				<td><%= @enabler.fax %></td>
			</tr>
			<tr>
				<td>Individual's Website Url:</td>
				<td><%= @enabler.indiv_web_url %></td>
			</tr>
			<tr>
				<td>Individual's Description:</td>
				<td><%= @enabler.indiv_description %></td>
			</tr>
			<tr>
				<td>Individual Notes:</td>
				<td><%= @enabler.indiv_notes %></td>
			</tr>
			<tr>
				<td>Work Address Street:</td>
				<td><%= @enabler.work_address_street %></td>
			</tr>
			<tr>
				<td>Work Address City:</td>
				<td><%= @enabler.work_address_city %></td>
			</tr>
			<tr>
				<td>Work Address State:</td>
				<td><%= @enabler.work_address_state %></td>
			</tr>
			<tr>
				<td>Work Address Zip:</td>
				<td><%= @enabler.work_address_zip %></td>
			</tr>
						<tr>
				<td>Home Address Street:</td>
				<td><%= @enabler.home_address_street %></td>
			</tr>
			<tr>
				<td>Home Address City:</td>
				<td><%= @enabler.home_address_city %></td>
			</tr>
			<tr>
				<td>Home Address State:</td>
				<td><%= @enabler.home_address_state %></td>
			</tr>
			<tr>
				<td>Home Address Zip:</td>
				<td><%= @enabler.home_address_zip %></td>
			</tr>
			<tr>
				<td>Spousal Status:</td>
				<td><%= @enabler.spousal_status %></td>
			</tr>
			<tr>
				<td>Spouse's Name:</td>
				<td><%= @enabler.spouse_name %></td>
			</tr>
			<tr>
				<td>Orientation:</td>
				<td><%= @enabler.orientation %></td>
			</tr>
			<tr>
				<td>Gender:</td>
				<td><%= @enabler.gender %></td>
			</tr>
			<tr>
				<td>Ethnicity/Race:</td>
				<td><%= @enabler.ethnicity %></td>
			</tr>
			<tr>
				<td>Country of Origin:</td>
				<td><%= @enabler.country_of_origin %></td>
			</tr>
			<tr>
				<td>Major Deals:</td>
				<td><%= @enabler.major_deals %></td>
			</tr>
			<tr>
				<td>Staff Notes:</td>
				<td><%= @enabler.staff_notes %></td>
			</tr>
			<tr>
				<td>Twitter Account Link:</td>
				<td><%= @enabler.social_twitter %></td>
			</tr>
			<tr>
				<td>Linked-In Account Link:</td>
				<td><%= @enabler.social_linkedin %></td>
			</tr>
			<tr>
				<td>Facebook Account Link:</td>
				<td><%= @enabler.social_facebook %></td>
			</tr>
			<tr>
				<td>Google + Account Link:</td>
				<td><%= @enabler.social_googleplus %></td>
			</tr>
			<tr>
				<td>YouTube Account Link:</td>
				<td><%= @enabler.social_youtube %></td>
			</tr>
			<tr>
				<td>Pinterest Account Link:</td>
				<td><%= @enabler.social_pinterest %></td>
			</tr>
			<tr>
				<td>Instagram Account Link:</td>
				<td><%= @enabler.social_instagram %></td>
			</tr>
			<tr>
				<td>Flickr Account Link:</td>
				<td><%= @enabler.social_flickr %></td>
			</tr>
			<tr>
				<td>Blog Link:</td>
				<td><%= @enabler.social_blog %></td>
			</tr>
			<tr>
				<td>Dominant/Preffered Social Media Platform:</td>
				<td><%= @enabler.social_platform_dominant %></td>
			</tr>
			<tr>
				<td>Date Last Updated:</td>
				<td><%= @enabler.date_last_updated %></td>
			</tr>			
			</tbody>
		</table>