config/routes.rb
Rails.application.routes.draw do

get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'

resources :users
resources :sessions

root 'organizations#index'

  get 'enablers/' => 'enablers#index', as: :enablers
  get 'enablers/new' => 'enablers#new', as: :new_enabler
  get 'enablers/:id' => 'enablers#show', as: :enabler
  post 'enablers/' => 'enablers#create', as: :create_enabler
  get 'enablers/:id/edit' => 'enablers#edit', as: :edit_enabler
  patch 'enablers/:id' => 'enablers#update', as: :update_enabler
  delete 'enablers/:id' => 'enablers#destroy', as: :delete_enabler

  get 'organizations/' => 'organizations#index', as: :organizations
  get 'organizations/new' => 'organizations#new', as: :new_organization
  get 'organizations/:id' => 'organizations#show', as: :organization
  post 'organizations/' => 'organizations#create', as: :create_organization
  get 'organizations/:id/edit' => 'organizations#edit', as: :edit_organization
  patch 'organizations/:id' => 'organizations#update', as: :update_organization
  delete 'organizations/:id' => 'organizations#destroy', as: :delete_organization

end

app/models/organization.rb
class Organization
  include Mongoid::Document
  field :name, type: String
  field :type, type: String
  field :web_url, type: String
  field :description, type: String
  field :notes, type: String
  field :vision, type: String
  field :mission, type: String
  field :goals, type: String
  field :values, type: String
  field :motto, type: String
  field :parent_or_child, type: String
  field :size_revenue, type: String
  field :size_revenue_date_last_updated, type: DateTime
  field :size_employees, type: String
  field :size_employees_date_last_updated, type: DateTime
  field :hq_address_street, type: String
  field :hq_address_city, type: String
  field :hq_address_state, type: String
  field :hq_address_zip, type: String
  field :hq_tel, type: String
  field :hq_email, type: String
  field :date_org_founded, type: DateTime
  field :region_headquartered_in, type: String
  # should I have major deals here, since I will have a deals model and a connection through the relationship?
  field :major_deals, type: String
  field :social_twitter, type: String
  field :social_linkedin, type: String
  field :social_facebook, type: String
  field :social_googleplus, type: String
  field :social_youtube, type: String
  field :social_platform_dominant, type: String
  field :company_classification_type, type: String
  field :company_size_structured, type: String
  field :company_special_designations, type: String
  field :ct_constituency_type, type: String
  field :date_last_updated, type: DateTime

  has_many :org_ena_join_tables

  def enablers
    Enabler.find enabler_ids
  end

  def enabler_ids
    enabler_ids_array = []
    self.org_ena_join_tables.each do |one_joining|
      if one_joining.enabler_id
        enabler_ids_array.push one_joining.enabler_id
      end 
    end
    enabler_ids_array 
  end

  def enabler_ids=(list)
    self.org_ena_join_tables.destroy
    list.each do |enabler_id|
      self.org_ena_join_tables.create(enabler_id: enabler_id)
    end
  end

  # some way of showing a list
  def join_list
    enablers_string = ""
    enablers.each do |one_enabler|
      enablers_string += " " + one_enabler.name
    end
    enablers_string.slice(2,enablers_string.length - 1)
    enablers_string
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
	
# before_action :make_sure_logged_in

before_filter :authorize

	def index
		@organizations = Organization.all
	end

	def show
		@organization = Organization.find(params[:id])
	end

	def new
		@organization = Organization.new
	end

	def create
		@organization = Organization.new(org_user_params)
		if @organization.save
			redirect_to organizations_path
		else
			render 'new'
		end
	end

	def edit
		@organization = Organization.find(params[:id])
	end

	def update
		@organization = Organization.find(params[:id])
		if @organization.update_attributes(org_user_params)
			redirect_to organizations_path
		else
			render 'edit'
		end
	end

	def destroy
		@organization = Organization.find(params[:id])
		@organization.destroy
		redirect_to organizations_path
	end

private

	def make_sure_logged_in
		if !current_user
		redirect_to new_session_path
		end
	end

	def org_user_params
    params.require(:organization).permit(
  		:name, 
  		:type, 
  		:web_url, 
  		:description, 
  		:notes, 
  		:vision, 
  		:mission, 
  		:goals, 
  		:values, 
  		:motto, 
  		:parent_or_child, 
  		:size_revenue, 
  		:size_revenue_date_last_updated, 
  		:size_employees, 
  		:size_employees_date_last_updated, 
  		:hq_address_street, 
  		:hq_address_city, 
  		:hq_address_state, 
  		:hq_address_zip, 
  		:hq_tel, 
  		:hq_email, 
  		:date_org_founded, 
  		:region_headquartered_in, 
  		# should I have major deals here, since I will have a deals model and a connection through the relationship?
  		:major_deals, 
  		:social_twitter, 
  		:social_linkedin, 
  		:social_facebook, 
  		:social_googleplus, 
  		:social_youtube, 
  		:social_platform_dominant, 
  		:company_classification_type, 
  		:company_size_structured, 
  		:company_special_designations, 
  		:ct_constituency_type, 
  		:date_last_updated, 
  		enabler_ids: []
		)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form_new_edit.html.erb
<%= form_for @organization do |f| %>

<div class="wrapper_div">
	<div class="center_div">
		<table>
			<tbody>
			<tr>
            <td>Organization Name:</td>
            <td><%= f.text_field :name %></td>
         </tr>
         <tr>
            <td>Type of Organization:</td>
            <td><%= f.text_field :type %></td>
         </tr>
         <tr>
            <td>Website url:</td>
            <td><%= f.text_field :web_url %></td>
         </tr>
         <tr>
            <td>Company Description</td>
            <td><%= f.text_field :description %>
            </td>
            </tr>
         <tr>
            <td>Notes </td>
            <td><%= f.text_field :notes %>
            </td>
            </tr>
         <tr>
            <td>Org's Vision</td>
            <td><%= f.text_field :vision %>
            </td>
            </tr>
         <tr>
            <td>Org's Mission</td>
            <td><%= f.text_field :mission %>
            </td>
            </tr>
         <tr>
            <td>Org's Goals</td>
            <td><%= f.text_field :goals %>
            </td>
            </tr>
         <tr>
            <td>Org's Values</td>
            <td><%= f.text_field :values %>
            </td>
            </tr>
         <tr>
            <td>Org's Motto or Tagline</td>
            <td><%= f.text_field :motto %>
            </td>
            </tr>
         <tr>
            <td>Is this a Parent Company or the subsidiary(child) of another company?</td>
            <td><%= f.text_field :parent_or_child %>
            </td>
            </tr>
         <tr>
            <td>Size of Org, in Revenue</td>
            <td><%= f.text_field :size_revenue %>
            </td>
            </tr>
         <tr>
            <td>Date Size by Revenue was last Updated</td>
            <td><%= f.datetime_field :size_revenue_date_last_updated %>
            </td>
         <tr>
            <td>Size of Org, by Number of Employees</td>
            <td><%= f.text_field :size_employees %>
            </td>
            </tr>
         <tr>
            <td>Date that Size by Employees was last Updated</td>
            <td><%= f.datetime_field :size_employees_date_last_updated %>
            </td>
         <tr>
            <td>Headquarters Address Street</td>
            <td><%= f.text_field :hq_address_street %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Address City</td>
            <td><%= f.text_field :hq_address_city %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Address State</td>
            <td><%= f.text_field :hq_address_state %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Address Zip</td>
            <td><%= f.text_field :hq_address_zip %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Telephone</td>
            <td><%= f.text_field :hq_tel %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Email</td>
            <td><%= f.text_field :hq_email %>
            </td>
            </tr>
         <tr>
            <td>Date Org was Founded</td>
            <td><%= f.datetime_field :date_org_founded %>
            </td>
         <tr>
            <td>Region in which the Org is Headquartered</td>
            <td><%= f.text_field :region_headquartered_in %>
            </td>
            </tr>
<!-- should I have major deals here, since I will have a deals model and a connection through the relationship? -->
         <tr>
            <td>Major Deals the Org has Been Involved In</td>
            <td><%= f.text_field :major_deals %>
            </td>
            </tr>
         <tr>
            <td>Twitter url:</td>
            <td><%= f.text_field :social_twitter %>
            </td>
            </tr>
         <tr>
            <td>Linked-In url:</td>
            <td><%= f.text_field :social_linkedin %>
            </td>
            </tr>
         <tr>
            <td>Facebook url:</td>
            <td><%= f.text_field :social_facebook %>
            </td>
            </tr>
         <tr>
            <td>Google+ url:</td>
            <td><%= f.text_field :social_googleplus %>
            </td>
            </tr>
         <tr>
            <td>YouTube url:</td>
            <td><%= f.text_field :social_youtube %>
            </td>
            </tr>
         <tr>
            <td>Preferred/Dominant/Most Utilized Social Media Platform</td>
            <td><%= f.text_field :social_platform_dominant %>
            </td>
            </tr>
         <tr>
            <td>Org Tech Classification</td>
            <td><%= f.text_field :company_classification_type %>
            </td>
            </tr>
         <tr>
            <td>Org Size, Structured</td>
            <td><%= f.text_field :company_size_structured %>
            </td>
            </tr>
         <tr>
            <td>Org Special Designations</td>
            <td><%= f.text_field :company_special_designations %></td>
         </tr>
         <tr>
            <td>CrossTech Constituent Type</td>
            <td><%= f.text_field :ct_constituency_type %>
            </td>
         </tr>
         <tr>
            <td>Date this Org's Record was last Updated</td>
            <td><%= f.datetime_field :date_last_updated %>
            </td>
         </tr>
         <tr>
            <td>Mark Executives affiliated with this Org:</td>
            <td> <%= f.collection_check_boxes :enabler_ids, Enabler.all, :id, :lastname %>
         </tr>
         <tr>
            <td> </td>
            <td><%= f.submit "Submit" %></td>
         </tr>
			</tbody>
		</table>
	</div>
</div>

<% end %>

app/views/organizations/edit.html.erb
<h1>Edit an Enabler Organization</h1>

<%= render 'form_new_edit' %>

app/views/organizations/index.html.erb
<div class="wrapper_div">
	<div class="center_div">
		<table>
			<thead>
			<tr class="row_odd">
				<th colspan="5"><h2 style="margin:20px">VIEW the "Organizations" enabling Tech Innovation</h2></th>
			</tr>
			<tr class="row_odd">
				<th><h2><u>Org Name</u></h2></th>
				<th><h2><u>Org Type</u></h2></th>
				<th><h2><u>Website</u></h2></th>
				<th><h2><u>Description</u></h2></th>
				<th><h2><u>Actions</u></h2></th>
			</tr>
			</thead>
			<tbody>
		<% @organizations.each do |organization| %>
			<tr>
				<td><strong><%= organization.name %></strong>
				</td>
				<td><strong><%= organization.type %></strong>
				</td>
				<td><%= organization.web_url %></strong>
				</td>
				<td><%= organization.description %></strong>
				</td>
				<td>
					<ul>
						<li><%= link_to 'Details', organization %></li>
						<li><%= link_to 'Edit', edit_organization_path(organization) %></li>
						<li><%= link_to 'Delete', organization, method: :delete, data: { confirm: 'Are you sure?' } %></li>
					</ul>
						</td>

			</tr>
			<% end %>
			</tbody>
		</table>

	</div>
</div>

app/views/organizations/new.html.erb
<h1>ADD a NEW Enabler Organization</h1>

<%= render 'form_new_edit' %>

app/views/organizations/show.html.erb
<div class="wrapper_div">
	<div class="center_div">
		<table>
			<thead>
			<tr class="row_odd">
				<th colspan="2"><h1 style="margin:20px">VIEW This Technology "Organization"</h1></th>
			</tr>
			</thead>
			<tbody>
		<tr>
            <td>Organization Name:</td>
            <td><%= @organization.name %></td>
         </tr>
         <tr>
            <td>Type of Organization:</td>
            <td><%= @organization.type %></td>
         </tr>
         <tr>
            <td>Website url:</td>
            <td><%= @organization.web_url %></td>
         </tr>
         <tr>
            <td>Company Description</td>
            <td><%= @organization.description %>
            </td>
            </tr>
         <tr>
            <td>Notes </td>
            <td><%= @organization.notes %>
            </td>
            </tr>
         <tr>
            <td>Org's Vision</td>
            <td><%= @organization.vision %>
            </td>
            </tr>
         <tr>
            <td>Org's Mission</td>
            <td><%= @organization.mission %>
            </td>
            </tr>
         <tr>
            <td>Org's Goals</td>
            <td><%= @organization.goals %>
            </td>
            </tr>
         <tr>
            <td>Org's Values</td>
            <td><%= @organization.values %>
            </td>
            </tr>
         <tr>
            <td>Org's Motto or Tagline</td>
            <td><%= @organization.motto %>
            </td>
            </tr>
         <tr>
            <td>Is this a Parent Company or the subsidiary(child) of another company?</td>
            <td><%= @organization.parent_or_child %>
            </td>
            </tr>
         <tr>
            <td>Size of Org, in Revenue</td>
            <td><%= @organization.size_revenue %>
            </td>
            </tr>
         <tr>
            <td>Date Size by Revenue was last Updated</td>
            <td><%= @organization.size_revenue_date_last_updated %>
            </td>
         <tr>
            <td>Size of Org, by Number of Employees</td>
            <td><%= @organization.size_employees %>
            </td>
            </tr>
         <tr>
            <td>Date that Size by Employees was last Updated</td>
            <td><%= @organization.size_employees_date_last_updated %>
            </td>
         <tr>
            <td>Headquarters Address Street</td>
            <td><%= @organization.hq_address_street %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Address City</td>
            <td><%= @organization.hq_address_city %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Address State</td>
            <td><%= @organization.hq_address_state %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Address Zip</td>
            <td><%= @organization.hq_address_zip %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Telephone</td>
            <td><%= @organization.hq_tel %>
            </td>
            </tr>
         <tr>
            <td>Headquarters Email</td>
            <td><%= @organization.hq_email %>
            </td>
            </tr>
         <tr>
            <td>Date Org was Founded</td>
            <td><%= @organization.date_org_founded %>
            </td>
         <tr>
            <td>Region in which the Org is Headquartered</td>
            <td><%= @organization.region_headquartered_in %>
            </td>
            </tr>
<!-- should I have major deals here, since I will have a deals model and a connection through the relationship? -->
         <tr>
            <td>Major Deals the Org has Been Involved In</td>
            <td><%= @organization.major_deals %>
            </td>
            </tr>
         <tr>
            <td>Twitter url:</td>
            <td><%= @organization.social_twitter %>
            </td>
            </tr>
         <tr>
            <td>Linked-In url:</td>
            <td><%= @organization.social_linkedin %>
            </td>
            </tr>
         <tr>
            <td>Facebook url:</td>
            <td><%= @organization.social_facebook %>
            </td>
            </tr>
         <tr>
            <td>Google+ url:</td>
            <td><%= @organization.social_googleplus %>
            </td>
            </tr>
         <tr>
            <td>YouTube url:</td>
            <td><%= @organization.social_youtube %>
            </td>
            </tr>
         <tr>
            <td>Preferred/Dominant/Most Utilized Social Media Platform</td>
            <td><%= @organization.social_platform_dominant %>
            </td>
            </tr>
         <tr>
            <td>Org Tech Classification</td>
            <td><%= @organization.company_classification_type %>
            </td>
            </tr>
         <tr>
            <td>Org Size, Structured</td>
            <td><%= @organization.company_size_structured %>
            </td>
            </tr>
         <tr>
            <td>Org Special Designations</td>
            <td><%= @organization.company_special_designations %></td>
         </tr>
         <tr>
            <td>CrossTech Constituent Type</td>
            <td><%= @organization.ct_constituency_type %>
            </td>
         </tr>
         <tr>
            <td>Date this Org's Record was last Updated</td>
            <td><%= @organization.date_last_updated %>
            </td>
         </tr>
			<tr style="background-color:#055154">
				<td style="font-weight:normal"><br>
					<%= link_to "Return to the list of Organizations!", organizations_path %></td>
				<td><br>
					<%= link_to "Delete this Organization!", :enabler, method: :delete, data: {confirm: "Are you sure you want to delete this Organization?"} %></td>
			</tr>
			</tbody>
		</table>
<br><br>
<p>Here is data from all the enabler executive records that match:<br>
   <%= @join_list %></p>
	</div>
</div>