config/routes.rb
Rails.application.routes.draw do

get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'

resources :users
resources :sessions

root 'organizations#index'

  get 'enablers/' => 'enablers#index', as: :enablers
  get 'enablers/new' => 'enablers#new', as: :new_enabler
  get 'enablers/:id' => 'enablers#show', as: :enabler
  post 'enablers/' => 'enablers#create', as: :create_enabler
  get 'enablers/:id/edit' => 'enablers#edit', as: :edit_enabler
  patch 'enablers/:id' => 'enablers#update', as: :update_enabler
  delete 'enablers/:id' => 'enablers#destroy', as: :delete_enabler

  get 'organizations/' => 'organizations#index', as: :organizations
  get 'organizations/new' => 'organizations#new', as: :new_organization
  get 'organizations/:id' => 'organizations#show', as: :organization
  post 'organizations/' => 'organizations#create', as: :create_organization
  get 'organizations/:id/edit' => 'organizations#edit', as: :edit_organization
  patch 'organizations/:id' => 'organizations#update', as: :update_organization
  delete 'organizations/:id' => 'organizations#destroy', as: :delete_organization

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crosstech PipeLine Enablers and Players Tracking</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- FONTS I might want to use -->
  <link href='http://fonts.googleapis.com/css?family=Voces' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Nova+Round' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Cinzel:400,700,900' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Quattrocento:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper_div">
    <div class="center_div">
    <div class="header_content">
    <img src="../../assets/CTX-Logo-wide-short.jpg"><br><div id="container">
      <div id="user_header">
   <% if current_user %>
      Logged in as Username: <%= current_user.username %>.
      <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %> or
      <%= link_to "Login", login_path %>
    <% end %>
      </div><br>
  <h1><i>SciTech PipeLine Enablers</i></h1>
  <h2>Tracking the Orgs, Execs, Deals &amp; Consultants<br> that Enable Startup Success</i></h2>
  </div>

<%= yield %>

   </div>
   <br>
   <hr>
   <br>

<table class="footer_table">
    <tr><u>
        <td><b>ENABLER EXECUTIVES</b></td>
      <td><b>ENABLER ORGANIZATIONS</b></td>
    </u>
    </tr>
      <tr>
        <td>
        <%= link_to 'Add a New Exec', new_enabler_path %> &nbsp;&nbsp;| &nbsp;&nbsp;
        <%= link_to 'View All Executives', enablers_path %>
        </td>
        <td>
        <%= link_to 'Add a New Organization', new_organization_path %> &nbsp;&nbsp;| &nbsp;&nbsp;
        <%= link_to 'View All Organizations', organizations_path %>
        <br>
        </td>
    </tr>
</table>

 </div>
</div>
</body>
</html>